-- Script generated by Redgate Compare v1.64.0.5717


-- deployment: Dropping PUBLIC.CUSTOMER_ORDER_SUMMARY...
DROP VIEW PUBLIC.CUSTOMER_ORDER_SUMMARY;


-- deployment: Dropping PUBLIC.ORDER_EVENTS...
DROP TABLE PUBLIC.ORDER_EVENTS; -- noqa: RG01


-- deployment: Dropping PUBLIC.ORDERS...
DROP TABLE PUBLIC.ORDERS; -- noqa: RG01


-- deployment: Dropping PUBLIC.CUSTOMERS...
DROP TABLE PUBLIC.CUSTOMERS; -- noqa: RG01

